---
title: Eric Gross
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: e@ericgross.com
description: A bunch of content about what I have learned.
baseurl: ''
url: https://ericgross.com
twitter_username: eric_gross_nyc
github_username: ericgross
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
search_enabled: false
plugins:
- jekyll-feed
- 
exclude:
- Gemfile
- Gemfile.lock
- ".idea/"
